-- ============================================
-- 02 - CREATE TABLESPACES  
-- GROUP B – ESDS PROJECT
-- ============================================

ALTER SESSION SET container = B_28741_ESDS_PDB;

CREATE TABLESPACE B_28741_ESDS_TBS
  DATAFILE 'B_28741_ESDS_TBS.dbf'
  SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

CREATE TEMPORARY TABLESPACE B_28741_ESDS_TEMP
  TEMPFILE 'B_28741_ESDS_TEMP.dbf'
  SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;

