-- ============================================
-- 03 - CREATE ADMIN + SCHEMA USER  
-- GROUP B – ESDS PROJECT
-- ============================================

ALTER SESSION SET container = B_28741_ESDS_PDB;

-- Admin user
CREATE USER B_28741_ESDS_ADMIN IDENTIFIED BY Admin123
  DEFAULT TABLESPACE B_28741_ESDS_TBS
  TEMPORARY TABLESPACE B_28741_ESDS_TEMP
  QUOTA UNLIMITED ON B_28741_ESDS_TBS;

GRANT CONNECT, RESOURCE, CREATE SESSION, DBA TO B_28741_ESDS_ADMIN;


-- Schema user
CREATE USER B_28741_ESDS_USER IDENTIFIED BY User123
  DEFAULT TABLESPACE B_28741_ESDS_TBS
  TEMPORARY TABLESPACE B_28741_ESDS_TEMP
  QUOTA UNLIMITED ON B_28741_ESDS_TBS;

GRANT CONNECT, RESOURCE, CREATE SESSION TO B_28741_ESDS_USER;


